# This is a basic workflow to help you get started with Actions

name: DevOps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a file to save Droplet IP Address
        run: |
          touch data.txt
          
      - name: Create a Docker based Droplet
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          # Ansible playbook filepath
          playbook: '.github/playbook.yml' 
          
      - name: Save Droplet IP Address in Environment Variable
        run: |
          echo "IP_ADDRESS=$(cat data.txt)" >> $GITHUB_ENV
          sleep 10s
          
      - name: Save Droplet IP Address in Github Secrets
        uses: gliech/create-github-secret-action@v1.4.8
        with:
          # Name of the secret that you want to create/update
          name: SSH_HOST
          # Value of the secret that you want to create/update
          value: ${{env.IP_ADDRESS}}
          # Personal access token with permission to modify repository or organization secrets
          pa_token: ${{secrets.PA_TOKEN}}
          
      - name: Deploying UnSAFE Bank
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{env.IP_ADDRESS}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            mkdir -p /opt/app
            cd /opt/app
            git clone https://github.com/rubaljain/UnSAFE_Bank
            cd UnSAFE_Bank/Backend
            docker-compose up -d
            
      - name: Setup Selenium and Chrome Web Drivers
        run: |
            pip3 install selenium
            sudo apt-get install default-jdk
            sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
            echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get -y update
            sudo apt-get -y install google-chrome-stable
            sudo wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/chromedriver
            sudo chown root:root /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver
            
      - name: Run Login Test
        run: python3 .github/unsafe_tests.py ${{env.IP_ADDRESS}}
        
      - name: UnSAFE Bank Application URL
        run: echo "Application URL  http://${{ env.IP_ADDRESS }}:3000"
