# This is a basic workflow to help you get started with Actions

name: DevSecOps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out repository
        uses: actions/checkout@v2
          
#       - name: Performing Automated Code Review using Codacy
#         uses: codacy/codacy-analysis-cli-action@4.0.0
#         with:
#           api-token: ${{ secrets.CODACY_TOKEN }}
#           output: codacy.sarif
#           format: sarif
#           # Adjust severity of non-security issues
#           gh-code-scanning-compat: true
#           # Force 0 exit code to allow SARIF file generation
#           # This will handover control about PR rejection to the GitHub side
#           max-allowed-issues: 2147483647
          
#       - name: Preparing Automated Code Review Results
#         run: |
#           pwd
#           ls
#           curl --upload-file ./codacy.sarif https://transfer.sh/codacy.sarif
          
#       - name: Finishing Automated Code Review Results 
#         uses: github/codeql-action/upload-sarif@v1
#         with:
#           sarif_file: codacy.sarif
      
      - name: Initiating Sensitive Information Scan using Truffle Hog
        run: |
          pip3 install truffleHog
          trufflehog --json ./ > out.json
          ls
          curl --upload-file ./out.json https://transfer.sh/out.json
#       - name: trufflehog-actions-scan
#         uses: edplato/trufflehog-actions-scan@master
#         with:
#           scanArguments: "--json" # Add custom options here*
      
      - name: Preparing Automated Code Review Results
        run: |
          ls
