# This is a basic workflow to help you get started with Actions

name: DevSecOps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
#    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   Automated_Code_Review:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checking out repository
#         uses: actions/checkout@v2
          
#       - name: Performing Automated Code Review using Codacy
#         uses: codacy/codacy-analysis-cli-action@4.0.0
#         with:
#           api-token: ${{ secrets.CODACY_TOKEN }}
#           output: codacy.sarif
#           format: sarif
#           # Adjust severity of non-security issues
#           gh-code-scanning-compat: true
#           # Force 0 exit code to allow SARIF file generation
#           # This will handover control about PR rejection to the GitHub side
#           max-allowed-issues: 2147483647
          
#       - name: Preparing Automated Code Review Results
#         run: |
#           pwd
#           ls
#           curl --upload-file ./codacy.sarif https://transfer.sh/codacy.sarif
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=SARIF" -F "file=@codacy.sarif" -F "engagement=24" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222"
          
# #       - name: Finishing Automated Code Review Results 
# #         uses: github/codeql-action/upload-sarif@v1
# #         with:
# #           sarif_file: codacy.sarif
      
# #       - name: Scanning for Sensitive Information using Truffle Hog
# #         uses: appleboy/ssh-action@v0.1.4
# #         with:
# #           host: ${{secrets.SSH_HOST}}
# #           key: ${{secrets.SSH_KEY}}
# #           username: ${{secrets.SSH_USERNAME}}
          
# #           script: |
# #             sudo apt update
# #             apt install -y python3-pip
# #             pip3 install truffleHog3
# #             cd /opt/app/UnSAFE_Bank/
# #             trufflehog3 --no-history --format json --output trufflehog.json
# #             trufflehog3 -R trufflehog.json --output trufflehog.html
# #             curl --upload-file ./trufflehog.html https://transfer.sh/trufflehog.html

#   Sensitive_Information_Scan:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
# #     permissions:
# #       actions: read
# #       contents: read
# #       security-events: write
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checking out repository
#         uses: actions/checkout@v2

#       - name: Initiating Sensitive Information Scan using Truffle Hog
#         run: |
#            pip install truffleHog
#            set +e
#            trufflehog --json . > trufflehog.json
#            curl --upload-file ./trufflehog.json https://transfer.sh/trufflehog.json
#            curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=Trufflehog Scan" -F "file=@trufflehog.json;type=application/json" -F "engagement=24" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222"
  
#   Software_Composition_Analysis:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
# #     permissions:
# #       actions: read
# #       contents: read
# #       security-events: write
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checking out repository
#         uses: actions/checkout@v2
        
#       - name: Performing Software Composition Analysis
#         uses: dependency-check/Dependency-Check_Action@main
#         id: Depcheck
#         with:
#           project: 'test'
#           path: '.'
#           format: 'XML'    
#           others: ''
          
#       - name: Preparing Software Composition Analysis Results
#         uses: actions/upload-artifact@master
#         with:
#            name: Depcheck report
#            path: ${{github.workspace}}/reports
           
#       - name: Finalizing Software Composition Analysis Results
#         run: |
#           cd reports
#           ls
#           curl --upload-file ./dependency-check-report.xml https://transfer.sh/dependency-check-report.xml
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=Dependency Check Scan" -F "file=@dependency-check-report.xml;type=text/xml" -F "engagement=24" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222"

#   Static_Appliation_Security_Testing:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
# #     permissions:
# #       actions: read
# #       contents: read
# #       security-events: write
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checking out repository
#         uses: actions/checkout@v2
        
#       - name: Performing SAST using Sonar Cloud
#         uses: sonarsource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SC_TOKEN }}
#         with:
#           args: >
#             -Dsonar.organization=lucideus
#             -Dsonar.projectKey=rubaljain_UnSAFE_Bank
#             -Dsonar.c.file.suffixes=-
#             -Dsonar.cpp.file.suffixes=-
#             -Dsonar.objc.file.suffixes=-

#       - name: Preparing SAST Results
#         run: |
#           npm install -g sonar-report 
#           cd /usr/local/lib/node_modules/sonar-report/
#           rm index.js
#           cp /home/runner/work/UnSAFE_Bank/UnSAFE_Bank/.github/index.js /usr/local/lib/node_modules/sonar-report/
#           npm install
#           cd /home/runner/work/UnSAFE_Bank/UnSAFE_Bank
#           sonar-report --sonarurl="https://sonarcloud.io" --project="rubaljain_UnSAFE_Bank" --application="UnSAFE_Bank"  --sonarorganization="lucideus" --sonarcomponent="rubaljain_UnSAFE_Bank" > sonarcloud.html
#           curl --upload-file sonarcloud.html https://transfer.sh/sonarcloud.html
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=SonarQube Scan detailed" -F "file=@sonarcloud.html;type=text/html" -F "engagement=24" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222"

#   Dynamic_Application_Security_Testing:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
# #     permissions:
# #       actions: read
# #       contents: read
# #       security-events: write
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checking out repository
#         uses: actions/checkout@v2
        
#       - name: Performing DAST using ZAP
#         uses: zaproxy/action-baseline@v0.4.0
#         with:
#           target: format('https://{0}:3000', secrets.SSH_HOST)
#           fail_action: false
#           token: ${{secrets.GITHUB_TOKEN}}
#           issue_title: ZAP Scan
#           cmd_options: '-x report_xml.xml'

#       - name: Preparing DAST Results
#         run: |
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=ZAP Scan" -F "file=@report_xml.xml;type=text/xml" -F "engagement=24" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222"

  Container Vulnerability Scanning:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out repository
        uses: actions/checkout@v2
        
      - name: Building Application Containers
        run: |
          cd Backend
          docker-compose up -d
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend_php
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          
      - name: Building Application Containers
        run: |
          cd Backend
          docker-compose up -d
        
#   Compliance_as_Code:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checking out repository
#         uses: actions/checkout@v2
        
#       - name: Building Application Containers
#         run: |
#           cd Backend
#           docker-compose up -d
      
#       - name: Testing Backend Container
#         uses: erzz/dockle-action@v1.0.0
#         with:
#           image: backend_php
#           report-format: sarif
#           report-name: backend_php

#       - name: Testing Frontend Container
#         uses: erzz/dockle-action@v1.0.0
#         with:
#           image: backend_web
#           report-format: sarif
#           report-name: backend_web
          
#       - name: Testing Web Server Container
#         uses: erzz/dockle-action@v1.0.0
#         with:
#           image: backend_server
#           report-format: sarif
#           report-name: backend_server

#       - name: Testing Database Container
#         uses: erzz/dockle-action@v1.0.0
#         with:
#           image: backend_db
#           report-format: sarif
#           report-name: backend_db

#       - name: Preparing Compliance Results
#         run: |
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=SARIF" -F "file=@backend_php.sarif" -F "engagement=25" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 17c1ee70ae82a45918e277636f1193f1acfe6c35"
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=SARIF" -F "file=@backend_server.sarif" -F "engagement=25" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 17c1ee70ae82a45918e277636f1193f1acfe6c35"
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=SARIF" -F "file=@backend_db.sarif" -F "engagement=25" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 17c1ee70ae82a45918e277636f1193f1acfe6c35"
#           curl -X POST "https://demo.defectdojo.org/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "minimum_severity=Info" -F "active=true" -F "verified=false" -F "scan_type=SARIF" -F "file=@backend_web.sarif" -F "engagement=25" -F "close_old_findings=false" -F "push_to_jira=false" -H "Authorization: Token 17c1ee70ae82a45918e277636f1193f1acfe6c35"

