# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          # Ansible playbook filepath
          playbook: '.github/workflows/playbook.yml'
          
      - name: save ip and hostname to local hosts file /etc/hosts
        uses: actions/checkout@v2
        become: yes
        lineinfile:
          path: /etc/hosts
          regexp: '.*{{ item.data.droplet.name }}$'
          line: "{{ item.data.ip_address }}  {{ item.data.droplet.name }}"
        with_items: "{{ droplet_result.results }}"

